INSERT INTO REQUEST_DETAILS (REQUESTDETAILSID,NUMBEROFCITIES,ORIGINCITY,MATRIX,REQUESTDETAILSDATE,SHORTESTPATH)	values ('REQ1212',5,2,'',SYSDATE,'22');
INSERT INTO REQUEST_DETAILS (REQUESTDETAILSID,NUMBEROFCITIES,ORIGINCITY,MATRIX,REQUESTDETAILSDATE,SHORTESTPATH)	values ('REQ1213',6,3,'',SYSDATE,'33');
INSERT INTO REQUEST_DETAILS (REQUESTDETAILSID,NUMBEROFCITIES,ORIGINCITY,MATRIX,REQUESTDETAILSDATE,SHORTESTPATH)	values ('REQ1214',7,5,'',SYSDATE,'22');
