INSERT INTO REQUEST_DETAILS (REQUESTDETAILSID,NUMBEROFCITIES,REQUESTDETAILSDATE)	values ('REQ1212','5',SYSDATE);
INSERT INTO REQUEST_DETAILS (REQUESTDETAILSID,NUMBEROFCITIES,REQUESTDETAILSDATE)	values ('REQ1213','6',SYSDATE);
INSERT INTO REQUEST_DETAILS (REQUESTDETAILSID,NUMBEROFCITIES,REQUESTDETAILSDATE)	values ('REQ1214','7',SYSDATE);

INSERT INTO MATRIXINPUT (MATRIXDETAILSID,REQUESTDETAILSID,REQUESTDETAILSDATE) values ('REQ1212','REQ1212',SYSDATE);
