
DROP TABLE IF EXISTS REQUEST_DETAILS;

CREATE TABLE REQUEST_DETAILS
(
  REQUESTDETAILSID     NVARCHAR2(50) NOT NULL PRIMARY KEY,
  NUMBEROFCITIES    NVARCHAR2(50)  DEFAULT NULL,
  REQUESTDETAILSDATE TIMESTAMP(6)
);

DROP TABLE IF EXISTS MATRIXINPUT;
CREATE TABLE MATRIXINPUT
(
  MATRIXDETAILSID     NVARCHAR2(50) NOT NULL PRIMARY KEY,
   REQUESTDETAILSID NVARCHAR2(50),
  REQUESTDETAILSDATE TIMESTAMP(6)
);

CREATE SEQUENCE REQUEST_DETAILS_SEQ start with 1 increment by 1 nocache;

CREATE SEQUENCE MATRIXINPUT_SEQ start with 1 increment by 1 nocache;

CREATE SEQUENCE REQUEST_NUMBER_SEQ start with 1001 increment by 1 nocache;

