
DROP TABLE IF EXISTS REQUEST_DETAILS;

CREATE TABLE REQUEST_DETAILS
(
  REQUESTDETAILSID     NVARCHAR2(50) NOT NULL PRIMARY KEY,
  NUMBEROFCITIES    NVARCHAR2(50)  DEFAULT NULL,
  ORIGINCITY  NVARCHAR2(50)  DEFAULT NULL,
  MATRIX ARRAY,
  REQUESTDETAILSDATE NVARCHAR2(50),
  SHORTESTPATH NVARCHAR2(100)
);


CREATE SEQUENCE REQUEST_DETAILS_SEQ start with 1 increment by 1 nocache;

CREATE SEQUENCE REQUEST_NUMBER_SEQ start with 1001 increment by 1 nocache;

